/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./node_modules/uni-comps-vue3/package/button/button.vue')['default']
    Checkbox: typeof import('./node_modules/uni-comps-vue3/package/checkbox/checkbox.vue')['default']
    CheckboxGroup: typeof import('./node_modules/uni-comps-vue3/package/checkbox-group/checkbox-group.vue')['default']
    Dialog: typeof import('./node_modules/uni-comps-vue3/package/dialog/dialog.vue')['default']
    Form: typeof import('./node_modules/uni-comps-vue3/package/form/form.vue')['default']
    FormItem: typeof import('./node_modules/uni-comps-vue3/package/form-item/form-item.vue')['default']
    Icon: typeof import('./node_modules/uni-comps-vue3/package/icon/icon.vue')['default']
    List: typeof import('./node_modules/uni-comps-vue3/package/list/list.vue')['default']
    Nav: typeof import('./node_modules/uni-comps-vue3/package/tab/nav.vue')['default']
    Navbar: typeof import('./node_modules/uni-comps-vue3/package/navbar/navbar.vue')['default']
    Popover: typeof import('./node_modules/uni-comps-vue3/package/popover/popover.vue')['default']
    Popup: typeof import('./node_modules/uni-comps-vue3/package/popup/popup.vue')['default']
    Radio: typeof import('./node_modules/uni-comps-vue3/package/radio/radio.vue')['default']
    RadioGroup: typeof import('./node_modules/uni-comps-vue3/package/radio-group/radio-group.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./node_modules/uni-comps-vue3/package/search/search.vue')['default']
    SlideAction: typeof import('./node_modules/uni-comps-vue3/package/slide-action/slide-action.vue')['default']
    SlideDelete: typeof import('./node_modules/uni-comps-vue3/package/slide-delete/slide-delete.vue')['default']
    Text: typeof import('./node_modules/uni-comps-vue3/package/text/text.vue')['default']
    Textarea: typeof import('./node_modules/uni-comps-vue3/package/textarea/textarea.vue')['default']
    VerifyCode: typeof import('./node_modules/uni-comps-vue3/package/verify-code/verify-code.vue')['default']
  }
}
